package com.s_space.trademanagementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class auditHistory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Comment")
	private java.lang.String comment;
	@org.kie.api.definition.type.Label("Username")
	private java.lang.String username;
	@org.kie.api.definition.type.Label("Rolename")
	private java.lang.String rolename;
	@org.kie.api.definition.type.Label(value = "Comment Date")
	private java.lang.String commentedDate;

	public auditHistory() {
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getRolename() {
		return this.rolename;
	}

	public void setRolename(java.lang.String rolename) {
		this.rolename = rolename;
	}

	public java.lang.String getCommentedDate() {
		return this.commentedDate;
	}

	public void setCommentedDate(java.lang.String commentedDate) {
		this.commentedDate = commentedDate;
	}

	public auditHistory(java.lang.String comment, java.lang.String username,
			java.lang.String rolename, java.lang.String commentedDate) {
		this.comment = comment;
		this.username = username;
		this.rolename = rolename;
		this.commentedDate = commentedDate;
	}

}