package com.s_space.trademanagementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Document() {
    }




}