package com.s_space.trademanagementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UploadedDocuments implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Documents")
	private java.util.List<com.s_space.trademanagementprocess.Document> documents;

	public UploadedDocuments() {
	}

	public java.util.List<com.s_space.trademanagementprocess.Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(
			java.util.List<com.s_space.trademanagementprocess.Document> documents) {
		this.documents = documents;
	}

	public UploadedDocuments(
			java.util.List<com.s_space.trademanagementprocess.Document> documents) {
		this.documents = documents;
	}

}