package com.s_space.trademanagementprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class UploadedDocument implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Documents")
	private java.util.List<com.s_space.trademanagementprocess.Document> document;

	public UploadedDocument() {
	}

	public java.util.List<com.s_space.trademanagementprocess.Document> getDocument() {
		return this.document;
	}

	public void setDocument(
			java.util.List<com.s_space.trademanagementprocess.Document> document) {
		this.document = document;
	}

	public UploadedDocument(
			java.util.List<com.s_space.trademanagementprocess.Document> document) {
		this.document = document;
	}

}